### ISSUE TITLE
Проблема с уведомлениями

### ISSUE THREAD

**Issue by Reidin-1** [keramzit69/MYBOTTODO#1]
Когда я указываю время прихода уведомления с напоминанием, то в указанное время оно не приходит. Изучая это, я наткнулся на это: /home/alexoff/git/python/prototypeTickTick/utils/sender.py. Видимо, используется какой-то скрипт. Вы можете с эти помочь?

**Comment by keramzit69** [comment]
Sorry I cant'
Btw how you found it

пт, 29 мар. 2024 г. в 05:11, Reidin ***@***.***>:
